[workspace]
member = ["crates/*"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[workspace.lints.clippy]
nursery = "warn"
perf = "warn"
pedantic = "warn"
style = "warn"
complexity = "warn"
suspicious = "warn"
